name: Cron

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:


jobs:
  discover-hn-mentions:
    name: Discover-Social-Mentions
    runs-on: ubuntu-latest
    env:
      DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
      REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
      REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
      REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}
      REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}
      REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD }}
      TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Install Node v16
        uses: actions/setup-node@v2.5.1
        with:
          node-version: '16'

      - name: Housekeeping
        run: yarn && yarn bootstrap

      - name: Run the script
        run: yarn lerna run --stream --scope @socialsnitch/cron prod